"use client";
import { useEffect, useState } from "react";
import type { AccountResponse } from "@/shared/contracts/user-management";
import { userManagementClient } from "../client";
export function AccountSettings() {
  const [account, setAccount] = useState<AccountResponse["user"]>(); const [error, setError] = useState<string>(); const [message, setMessage] = useState<string>();
  useEffect(() => { userManagementClient.getAccount().then((response) => setAccount(response.user)).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Unable to load account.")); }, []);
  async function saveProfile(data: FormData) { try { setError(undefined); const response = await userManagementClient.updateAccount(String(data.get("displayName"))); setAccount(response.user); setMessage("Profile updated."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update profile."); } }
  async function savePassword(data: FormData) { const current = String(data.get("currentPassword")); const next = String(data.get("newPassword")); if (next !== String(data.get("confirmPassword"))) { setError("New passwords do not match."); return; } try { setError(undefined); await userManagementClient.changePassword(current, next); setMessage("Password changed."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to change password."); } }
  if (!account && !error) return <main className="app-shell"><p role="status">Loading account…</p></main>;
  return <main className="app-shell"><header className="app-header"><div><p className="eyebrow">DPM / Account</p><h1>My profile</h1></div><a className="text-link" href="/users">Users &amp; Access</a></header><section className="panel"><form className="form-stack" action={saveProfile}><label>Display name<input name="displayName" autoComplete="name" defaultValue={account?.displayName} required /></label><label>Email<input value={account?.email ?? ""} type="email" disabled aria-describedby="email-note" readOnly /><span id="email-note">Email changes are not available here.</span></label><button className="button">Save profile</button></form><hr /><h2>Change password</h2><form className="form-stack" action={savePassword}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required /></label><label>New password<input name="newPassword" type="password" autoComplete="new-password" minLength={12} required /></label><label>Confirm new password<input name="confirmPassword" type="password" autoComplete="new-password" minLength={12} required /></label><button className="button">Change password</button></form>{error && <p className="error" role="alert">{error}</p>}{message && <p className="success" role="status">{message}</p>}</section></main>;
}
